name: nosnoc tests

on:
  pull_request:
  push:

jobs:
  test_nosnoc:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Python and pip package
      shell: bash
      run: |
        python3 --version
        sudo pip3 install virtualenv
        virtualenv --python=python3 env
        source env/bin/activate
        which python
        pip install -e .
        pip install -r requirements-test.txt

    - name: Run tests
      shell: bash
      run: |
        source env/bin/activate
        mkdir -p test-results
        python -m pytest --junitxml test-results/results.xml --cov=nosnoc --cov-report=html:test-results/coverage test

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'test-results/results.xml'

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/
